# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  run-tests:
    docker:
      - image: cimg/node:15.1
        # environment:
        #   DATABASE_URL: postgres://postgres:jasoncarr@localhost:5432/sdc_reviews

      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: jasoncarr
          POSTGRES_DB: sdc-reviews
    steps:
      # Checkout the code as the first step.
      - checkout
      # Next, the node orb's install-packages step will install the dependencies from a package.json.
      # The orb install-packages step will also automatically cache them for faster future runs.
      - node/install-packages
      # If you are using yarn instead npm, remove the line above and uncomment the two lines below.
      # - node/install-packages:
      #     pkg-manager: yarn
      - run:
          command: npm test

workflows:
  tests:
    jobs:
      - run-tests
      # - node/test:
      #     version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
      # build:
      #   docker:
      #     - image: circleci/postgres:9.6.5-alpine-ram
      #       environment:
      #         POSTGRES_USER: jasoncarr
      #         POSTGRES_DB: sdc-reviews


